/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2021-07-07 10:40:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/2021/Summer%202021%20(10-05%20to%2004-09)/PRJ301/Appolo-github/DemoProject/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1624378857782L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Metas -->\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Site Metas -->\r\n");
      out.write("        <title>List all products - DuniExchange</title>\r\n");
      out.write("        <meta name=\"keywords\" content=\"\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Site Icons -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Bootstrap CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <!-- Site CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("        <!-- Responsive CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("        <!-- Custom CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- Start Main Top -->\r\n");
      out.write("        <header class=\"main-header\">\r\n");
      out.write("            <!-- Start Navigation -->\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Start Header Navigation -->\r\n");
      out.write("                    <div class=\"navbar-header\">\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar-menu\" aria-controls=\"navbars-rs-food\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"index.html\"><img src=\"images/logo.png\" class=\"logo\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Header Navigation -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav ml-auto\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                            <li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.html\">Trang chủ</a></li>\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <p>SHOP</p>\r\n");
      out.write("                                    <i class=\"fas fa-caret-down\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"shop.html\">Sidebar Shop</a></li>\r\n");
      out.write("                                    <!-- <li><a href=\"shop-detail.html\">Shop Detail</a></li> -->\r\n");
      out.write("                                    <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                                    <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                                    <li><a href=\"myAccount.jsp\">My Account</a></li>\r\n");
      out.write("                                    <li><a href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"contact-us.html\">Liên hệ</a></li>\r\n");
      out.write("                            <li class=\"search-item\">\r\n");
      out.write("                                <!-- Start Top Search -->\r\n");
      out.write("                                <div class=\"search-toggle\">\r\n");
      out.write("                                    <div class=\"container\">\r\n");
      out.write("                                        <div id=\"search-group\" class=\"search-group close-search\">\r\n");
      out.write("                                            <div class=\"toggle-target-container\">\r\n");
      out.write("                                                <div class=\"toggle-target\"><input type=\"text\" class=\"search-text\" placeholder=\"Search\"></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"search-button-container\">\r\n");
      out.write("                                                <span class=\"input-group-addon search-button\"><i class=\"fa fa-search\" id=\"search-icon\"></i></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- End Top Search -->                            \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.navbar-collapse -->\r\n");
      out.write("                    <div id=\"login\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"login.html\">Đăng nhập</a>/<a class=\"nav-link\" href=\"register.html\">Đăng ký</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- End Navigation -->\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- End Main Top -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start Top Search -->\r\n");
      out.write("        <div class=\"top-search\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <span class=\"input-group-addon\"><i class=\"fa fa-search\"></i></span>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                    <span class=\"input-group-addon close-search\"><i class=\"fa fa-times\"></i></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Top Search -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start All Title Box -->\r\n");
      out.write("        <div class=\"all-title-box\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <h2>Shop</h2>\r\n");
      out.write("                        <ul class=\"breadcrumb\">\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item active\">Shop</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End All Title Box -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start Shop Page  -->\r\n");
      out.write("        <div class=\"shop-box-inner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right\">\r\n");
      out.write("                        <div class=\"right-product-box\">\r\n");
      out.write("                            <div class=\"product-item-filter row\">\r\n");
      out.write("                                <div class=\"col-12 col-sm-8 text-center text-sm-left\">\r\n");
      out.write("                                    <div class=\"toolbar-sorter-right\">\r\n");
      out.write("                                        <span>Sort by </span>\r\n");
      out.write("                                        <select id=\"basic\" class=\"selectpicker show-tick form-control\" data-placeholder=\"$ USD\">\r\n");
      out.write("                                            <option data-display=\"Select\">Nothing</option>\r\n");
      out.write("                                            <option value=\"1\">Popularity</option>\r\n");
      out.write("                                            <option value=\"2\">A → Z</option>\r\n");
      out.write("                                            <option value=\"3\">Z → A</option>\r\n");
      out.write("                                            <option value=\"4\">Best Trading</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>Showing all 4 results</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 col-sm-4 text-center text-sm-right\">\r\n");
      out.write("                                    <ul class=\"nav nav-tabs ml-auto\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a class=\"nav-link active\" href=\"#grid-view\" data-toggle=\"tab\"> <i class=\"fa fa-th\"></i> </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#list-view\" data-toggle=\"tab\"> <i class=\"fa fa-list-ul\"></i> </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"product-categorie-box\">\r\n");
      out.write("                                <div class=\"tab-content\">\r\n");
      out.write("                                    <div role=\"tabpanel\" class=\"tab-pane fade show active\" id=\"grid-view\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/Apollo-images/Big-images-A.png\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4><a href=\"product-detail.html\"> ÁO PHÔNG SẶC SỠ, SUÝT NỮA THÀNH ĐỒ GIA TRUYỀN NHƯNG NAY ĐƯỢC ĐEM RA ĐỔI</a></h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho (fake Uyen Trang)</a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"new\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-02.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-03.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 5 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"new\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-01.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-02.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-03.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-01.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"sale\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-02.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                <div class=\"products-single fix\">\r\n");
      out.write("                                                    <div class=\"box-img-hover\">\r\n");
      out.write("                                                        <div class=\"type-lb1\">\r\n");
      out.write("                                                            <p class=\"new\"></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <img src=\"images/img-pro-03.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                        <div class=\"mask-icon\">\r\n");
      out.write("                                                            <ul>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                            <a class=\"cart\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"why-text\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\"><a href=\"my-account.html\"> Dat Ho </a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"list-view\">\r\n");
      out.write("                                        <div class=\"list-view-box\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                    <div class=\"products-single fix\">\r\n");
      out.write("                                                        <div class=\"box-img-hover\">\r\n");
      out.write("                                                            <div class=\"type-lb1\">\r\n");
      out.write("                                                                <p class=\"new\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <img src=\"images/img-pro-01.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                            <div class=\"mask-icon\">\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-8 col-xl-8\">\r\n");
      out.write("                                                    <div class=\"why-text full-width\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p>Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus\r\n");
      out.write("                                                            sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.\r\n");
      out.write("                                                            Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.</p>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\" ><a href=\"my-account.html\" style=\"color: rgb(219, 169, 94);\"> Dat Ho</a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <a class=\"btn hvr-hover\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"list-view-box\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                    <div class=\"products-single fix\">\r\n");
      out.write("                                                        <div class=\"box-img-hover\">\r\n");
      out.write("                                                            <div class=\"type-lb1\">\r\n");
      out.write("                                                                <p class=\"sale\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <img src=\"images/img-pro-02.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                            <div class=\"mask-icon\">\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-8 col-xl-8\">\r\n");
      out.write("                                                    <div class=\"why-text full-width\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p>Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus\r\n");
      out.write("                                                            sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.\r\n");
      out.write("                                                            Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.</p>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\" ><a href=\"my-account.html\" style=\"color: rgb(219, 169, 94);\"> Dat Ho</a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <a class=\"btn hvr-hover\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"list-view-box\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                                                    <div class=\"products-single fix\">\r\n");
      out.write("                                                        <div class=\"box-img-hover\">\r\n");
      out.write("                                                            <div class=\"type-lb1\">\r\n");
      out.write("                                                                <p class=\"sale\"></p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <img src=\"images/img-pro-03.jpg\" class=\"img-fluid1\" alt=\"Image\">\r\n");
      out.write("                                                            <div class=\"mask-icon\">\r\n");
      out.write("                                                                <ul>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"View\"><i class=\"fas fa-eye\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Compare\"><i class=\"fas fa-sync-alt\"></i></a></li>\r\n");
      out.write("                                                                    <li><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Add to Wishlist\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-sm-6 col-md-6 col-lg-8 col-xl-8\">\r\n");
      out.write("                                                    <div class=\"why-text full-width\">\r\n");
      out.write("                                                        <h4>Lorem ipsum dolor sit amet</h4>\r\n");
      out.write("                                                        <p>Integer tincidunt aliquet nibh vitae dictum. In turpis sapien, imperdiet quis magna nec, iaculis ultrices ante. Integer vitae suscipit nisi. Morbi dignissim risus sit amet orci porta, eget aliquam purus\r\n");
      out.write("                                                            sollicitudin. Cras eu metus felis. Sed arcu arcu, sagittis in blandit eu, imperdiet sit amet eros. Donec accumsan nisi purus, quis euismod ex volutpat in. Vestibulum eleifend eros ac lobortis aliquet.\r\n");
      out.write("                                                            Suspendisse at ipsum vel lacus vehicula blandit et sollicitudin quam. Praesent vulputate semper libero pulvinar consequat. Etiam ut placerat lectus.</p>\r\n");
      out.write("                                                        <p style=\"float: right;\"><i class=\"fas fa-heart\" ></i> 15 </p>\r\n");
      out.write("                                                        <div class=\"Avatar\">\r\n");
      out.write("                                                            <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                                                 >\r\n");
      out.write("                                                            <p class=\"nameAva\" ><a href=\"my-account.html\" style=\"color: rgb(219, 169, 94);\"> Dat Ho</a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <p class=\"time\">\r\n");
      out.write("                                                            Mon, 31/05/2021\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <a class=\"btn hvr-hover\" href=\"#\">Add to Cart</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left\">\r\n");
      out.write("                        <div class=\"product-categori\">\r\n");
      out.write("                            <div class=\"search-product\">\r\n");
      out.write("                                <form action=\"#\">\r\n");
      out.write("                                    <input class=\"form-control\" placeholder=\"Search here...\" type=\"text\">\r\n");
      out.write("                                    <button type=\"submit\"> <i class=\"fa fa-search\"></i> </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"filter-sidebar-left\">\r\n");
      out.write("                                <div class=\"title-left\">\r\n");
      out.write("                                    <h3>Categories</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card bg-light mb-3\">\r\n");
      out.write("                                    <div class=\"card-header bg-success text-white text-uppercase\">Last product</div>\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <img class=\"img-fluid\" src=\"images/img-pro-03.jpg\" />\r\n");
      out.write("                                        <h5 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                                    <p class=\"card-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    <div class=\"like-progress\">\r\n");
      out.write("                                        <div class=\"icon-heart\"><i class=\"fas fa-heart\"></i> 20 </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"Avatar\">\r\n");
      out.write("                                        <img src=\"https://salt.tikicdn.com/cache/w444/ts/product/26/ee/55/48b7aed353fd452bd575b4822cd85214.jpg\" id=\"imgAva\" \r\n");
      out.write("                                             >\r\n");
      out.write("                                        <p class=\"nameAva\" ><a href=\"my-account.html\" style=\"color: rgb(219, 169, 94); font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\"> Dat Ho</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"time\">\r\n");
      out.write("                                        Mon, 31/05/2021\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Shop Page -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Instagram Feed  -->\r\n");
      out.write("    <div class=\"instagram-box\">\r\n");
      out.write("        <div class=\"main-instagram owl-carousel owl-theme\">\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-01.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-02.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-03.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-04.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-05.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-06.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-07.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-08.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-09.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"ins-inner-box\">\r\n");
      out.write("                    <img src=\"images/instagram-img-05.jpg\" alt=\"\" />\r\n");
      out.write("                    <div class=\"hov-in\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Instagram Feed  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Footer  -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-main\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row mr-3 col-lg-5\">\r\n");
      out.write("                    <div class=\"col-lg-6 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"footer-top-box\">\r\n");
      out.write("                            <h3>Nhận tin tức</h3>\r\n");
      out.write("                            <form class=\"newsletter-box\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input class=\"p-1\" type=\"email\" name=\"Email\" placeholder=\"Email Address*\" />\r\n");
      out.write("                                    <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\"btn hvr-hover\" type=\"submit\">Submit</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"footer-top-box\">\r\n");
      out.write("                            <h3>Mạng xã hội</h3>\r\n");
      out.write("                            <p>Biết thêm về chúng tôi tại</p>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-linkedin\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-rss\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-pinterest-p\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fab fa-whatsapp\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"footer-widget\">\r\n");
      out.write("                            <h4>Về DuniExchange</h4>\r\n");
      out.write("                            <p>Đây là một trong web dành cho trao đổi các vật phẩm của trường FPT</p> \r\n");
      out.write("                            <p>Những vật phẩm được trao đổi với nhau thông qua sự đồng ý giao dịch của 2 bên, trang web chỉ hỗ trợ tìm kiếm giao dịch, không tham gia vào quá trình giao dịch.</p>                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"footer-link\">\r\n");
      out.write("                            <h4>Information</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fas fa-angle-right\"></i> Về chúng tôi</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fas fa-angle-right\"></i> Dịch vụ khách hàng</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fas fa-angle-right\"></i> Điều khoản &amp; Điều kiện</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fas fa-angle-right\"></i> Chính sách bảo mật</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                        <div class=\"footer-link-contact\">\r\n");
      out.write("                            <h4>Contact Us</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <p><i class=\"fas fa-map-marker-alt\"></i>Địa chỉ: Trường Đại học FPT Đà Nẵng, Khu đô thị FPT City, Phường Hòa Hải, Quận Ngũ Hành Sơn, TP Đà Nẵng.\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <p><i class=\"fas fa-phone-square\"></i>Phone: <a href=\"tel:+1-888705770\">+1-888 705 770</a></p>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <p><i class=\"fas fa-envelope\"></i>Email: <a href=\"mailto:apolloteamproject@gmail.com\">apolloteamproject@gmail.com</a></p>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer  -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start copyright  -->\r\n");
      out.write("    <div class=\"footer-copyright\">\r\n");
      out.write("        <p class=\"footer-company\">All Rights Reserved. &copy; 2018 <a href=\"#\">ThewayShop</a> Design By :\r\n");
      out.write("            <a href=\"https://html.design/\">html design</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End copyright  -->\r\n");
      out.write("\r\n");
      out.write("    <a href=\"#\" id=\"back-to-top\" title=\"Back to top\" style=\"display: none;\">&uarr;</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ALL JS FILES -->\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- ALL PLUGINS -->\r\n");
      out.write("    <script src=\"js/jquery.superslides.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap-select.js\"></script>\r\n");
      out.write("    <script src=\"js/inewsticker.js\"></script>\r\n");
      out.write("    <script src=\"js/bootsnav.js.\"></script>\r\n");
      out.write("    <script src=\"js/images-loded.min.js\"></script>\r\n");
      out.write("    <script src=\"js/isotope.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/baguetteBox.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"js/form-validator.min.js\"></script>\r\n");
      out.write("    <script src=\"js/contact-form-script.js\"></script>\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("    <!-- Hữu Tình - 1208.03062021 - searchbar script -->\r\n");
      out.write("    <script src=\"js/searchbar.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /allProduct.jsp(583,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/allProduct.jsp(583,32) '${listC}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listC}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /allProduct.jsp(583,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("lC");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <div class=\"list-group list-group-collapse list-group-sm list-group-tree\" id=\"list-group-men\" data-children=\".sub-men\">\r\n");
            out.write("                                        <a href=\"#\" class=\"list-group-item list-group-item-action\"> lC.  <small class=\"text-muted\">(150) </small></a>\r\n");
            out.write("<!--                                        <a href=\"#\" class=\"list-group-item list-group-item-action\"> Điện tử  <small class=\"text-muted\">(150) </small></a>\r\n");
            out.write("                                        <a href=\"#\" class=\"list-group-item list-group-item-action\"> Đồ gia dụng  <small class=\"text-muted\">(150) </small></a>\r\n");
            out.write("                                        <a href=\"#\" class=\"list-group-item list-group-item-action\"> Giải trí  <small class=\"text-muted\">(150) </small></a>\r\n");
            out.write("                                        <a href=\"#\" class=\"list-group-item list-group-item-action\"> Thực phẩm  <small class=\"text-muted\">(150) </small></a>-->\r\n");
            out.write("                                    </div>");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
