/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2021-07-07 16:03:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/2021/Summer%202021%20(10-05%20to%2004-09)/PRJ301/Appolo-github/DemoProject/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1624378857782L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<!-- Basic -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\n");
      out.write("    <!-- Mobile Metas -->\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <!-- Site Metas -->\n");
      out.write("    <title>DuniExchange - nền tảng trao đổi sảm phẩm</title>\n");
      out.write("    <meta name=\"keywords\" content=\"\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <!-- Site Icons -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\n");
      out.write("\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("    <!-- Site CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    <!-- Responsive CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\n");
      out.write("\n");
      out.write("    <!-- lastestPost -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/lastestPost.css\">\n");
      out.write("    <!-- topLikePost -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/topLikePost.css\">\n");
      out.write("    <!-- The All Post -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/theAllPost.css\">\n");
      out.write("    <!-- The Exchanged Post -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/theExchangedPost.css\">\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write(" \n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Start Top Search -->\n");
      out.write("    <div class=\"top-search\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"input-group\">\n");
      out.write("                <span class=\"input-group-addon\"><i class=\"fa fa-search\"></i></span>\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n");
      out.write("                <span class=\"input-group-addon close-search\"><i class=\"fa fa-times\"></i></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End Top Search -->\n");
      out.write("\n");
      out.write("    <!-- Start Slider -->\n");
      out.write("    <div id=\"slides-shop\" class=\"cover-slides\">\n");
      out.write("        <ul class=\"slides-container\">\n");
      out.write("            <li class=\"text-center\">\n");
      out.write("                <img src=\"images/banner-01.jpg\" alt=\"\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> DuniExchange</strong></h1>\n");
      out.write("                            <p class=\"m-b-40\">Hope you have best time with us <br>Click button below.</p>\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Exchange Now</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"text-center\">\n");
      out.write("                <img src=\"images/banner-02.jpg\" alt=\"\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> DuniExchange</strong></h1>\n");
      out.write("                            <p class=\"m-b-40\">Hope you have best time with us <br>Click button below.</p>\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Exchange Now</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"text-center\">\n");
      out.write("                <img src=\"images/banner-03.jpg\" alt=\"\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <h1 class=\"m-b-20\"><strong>Welcome To <br> DuniExchange</strong></h1>\n");
      out.write("                            <p class=\"m-b-40\">Hope you have best time with us <br>Click button below.</p>\n");
      out.write("                            <p><a class=\"btn hvr-hover\" href=\"#\">Exchange Now</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"slides-navigation\">\n");
      out.write("            <a href=\"#\" class=\"next\"><i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a>\n");
      out.write("            <a href=\"#\" class=\"prev\"><i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i></a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End Slider -->\n");
      out.write("    <!-- lastest post -->\n");
      out.write("    <div class=\"lastestPost\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"postTitle\">\n");
      out.write("                    <h2>THE LASTEST POST</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"img1\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                        <div class=\"img2\"><img style=\"margin-left: -25%;\" src=\"img-test-lastest-post/people-2.jpg\"\n");
      out.write("                                alt=\"\"></div>\n");
      out.write("                        <div class=\"main-text\">\n");
      out.write("                            <h2>Nhat Quang LNN</h2>\n");
      out.write("                            <h3>Muốn đổi chiếc laptop này lấy gì chưa biết!</h3>\n");
      out.write("                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore, eos atque omnis,\n");
      out.write("                                tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                dolores reprehenderit aliquid! Ad excepturi quibusdam assumenda doloribus.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"socials\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                            <i class=\"fab fa-linkedin\"></i>\n");
      out.write("                            <i class=\"fab fa-youtube\"></i>\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"img1\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                        <div class=\"img2\"><img style=\"margin-left: -25%;\" src=\"img-test-lastest-post/people-2.jpg\"\n");
      out.write("                                alt=\"\"></div>\n");
      out.write("                        <div class=\"main-text\">\n");
      out.write("                            <h2>Nhat Quang LNN</h2>\n");
      out.write("                            <h3>Muốn đổi chiếc laptop này lấy gì chưa biết!</h3>\n");
      out.write("                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore, eos atque omnis,\n");
      out.write("                                tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                dolores reprehenderit aliquid! Ad excepturi quibusdam assumenda doloribus.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"socials\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                            <i class=\"fab fa-linkedin\"></i>\n");
      out.write("                            <i class=\"fab fa-youtube\"></i>\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"img1\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                        <div class=\"img2\"><img style=\"margin-left: -25%;\" src=\"img-test-lastest-post/people-2.jpg\"\n");
      out.write("                                alt=\"\"></div>\n");
      out.write("                        <div class=\"main-text\">\n");
      out.write("                            <h2>Nhat Quang LNN</h2>\n");
      out.write("                            <h3>Muốn đổi chiếc laptop này lấy gì chưa biết!</h3>\n");
      out.write("                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore, eos atque omnis,\n");
      out.write("                                tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                dolores reprehenderit aliquid! Ad excepturi quibusdam assumenda doloribus.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"socials\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                            <i class=\"fab fa-linkedin\"></i>\n");
      out.write("                            <i class=\"fab fa-youtube\"></i>\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"img1\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                        <div class=\"img2\"><img style=\"margin-left: -25%;\" src=\"img-test-lastest-post/people-2.jpg\"\n");
      out.write("                                alt=\"\"></div>\n");
      out.write("                        <div class=\"main-text\">\n");
      out.write("                            <h2>Nhat Quang LNN</h2>\n");
      out.write("                            <h3>Muốn đổi chiếc laptop này lấy gì chưa biết!</h3>\n");
      out.write("                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore, eos atque omnis,\n");
      out.write("                                tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                dolores reprehenderit aliquid! Ad excepturi quibusdam assumenda doloribus.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"socials\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                            <i class=\"fab fa-linkedin\"></i>\n");
      out.write("                            <i class=\"fab fa-youtube\"></i>\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- lastest post end-->\n");
      out.write("\n");
      out.write("    <!-- Top like Post -->\n");
      out.write("    <div class=\"topLikePost\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"postTitle\">\n");
      out.write("                    <h2>THE TOP LIKE POST</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card-container\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"front\">\n");
      out.write("                            <div class=\"avatar\">\n");
      out.write("                                <img src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <h2>Nhat Quang LNN</h2>\n");
      out.write("                                <div class=\"like\">\n");
      out.write("                                    <i class=\"fa fa-heart fa-3x\"></i>\n");
      out.write("                                    <div>3k2</div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <i class=\"fa fa-reply\"></i> View Post\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"back\">\n");
      out.write("                            <div class=\"product-img\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <div class=\"main-text-title\">\n");
      out.write("                                    <h3>Muốn đổi chiếc laptop này lấy gì chưa biết nơi</h3>\n");
      out.write("                                </div>\n");
      out.write("                                <p class=\"description\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore,\n");
      out.write("                                    eos atque omnis,\n");
      out.write("                                    tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                    dolores reprehenderit aliquid! Ad excepturi quibusdam description\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <div class=\"footer-to-align-center\">\n");
      out.write("                                    <!-- chỉ nên lấy 3 cái, lấy 4 cái bể -->\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-facebook\"></i> Máy tính</span>\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                    <span class=\"badge badge-success\"> <i class=\"fab fa-linkedin\"></i></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-4 \">\n");
      out.write("                <div class=\"card-container\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"front\">\n");
      out.write("                            <div class=\"avatar\">\n");
      out.write("                                <img src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <h2>Nhat Quang LNN</h2>\n");
      out.write("                                <div class=\"like\">\n");
      out.write("                                    <i class=\"fa fa-heart fa-3x\"></i>\n");
      out.write("                                    <div>3k2</div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <i class=\"fa fa-reply\"></i> View Post\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"back\">\n");
      out.write("                            <div class=\"product-img\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <div class=\"main-text-title\">\n");
      out.write("                                    <h3>Muốn đổi chiếc laptop này lấy gì chưa biết nơi</h3>\n");
      out.write("                                </div>\n");
      out.write("                                <p class=\"description\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore,\n");
      out.write("                                    eos atque omnis,\n");
      out.write("                                    tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                    dolores reprehenderit aliquid! Ad excepturi quibusdam description\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <div class=\"footer-to-align-center\">\n");
      out.write("                                    <!-- chỉ nên lấy 3 cái, lấy 4 cái bể -->\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-facebook\"></i> Máy tính</span>\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                    <span class=\"badge badge-success\"> <i class=\"fab fa-linkedin\"></i></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card-container\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"front\">\n");
      out.write("                            <div class=\"avatar\">\n");
      out.write("                                <img src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <h2>Nhat Quang LNN</h2>\n");
      out.write("                                <div class=\"like\">\n");
      out.write("                                    <i class=\"fa fa-heart fa-3x\"></i>\n");
      out.write("                                    <div>3k2</div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <i class=\"fa fa-reply\"></i> View Post\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"back\">\n");
      out.write("                            <div class=\"product-img\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                            <div class=\"main-text\">\n");
      out.write("                                <div class=\"main-text-title\">\n");
      out.write("                                    <h3>Muốn đổi chiếc laptop này lấy gì chưa biết nơi</h3>\n");
      out.write("                                </div>\n");
      out.write("                                <p class=\"description\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore,\n");
      out.write("                                    eos atque omnis,\n");
      out.write("                                    tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                    dolores reprehenderit aliquid! Ad excepturi quibusdam description\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <div class=\"footer-to-align-center\">\n");
      out.write("                                    <!-- chỉ nên lấy 3 cái, lấy 4 cái bể -->\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-facebook\"></i> Máy tính</span>\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                    <span class=\"badge badge-success\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                        tử</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Top like Post END -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- THE All Post -->\n");
      out.write("    <div class=\"theAllPost\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"postTitle\">\n");
      out.write("                    <h2>THE ALL POST</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <dvi class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- The left card -->\n");
      out.write("                <div class=\"col-md-8 the-left-card\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"card no-gutters offer-box-products\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-4 px-0\">\n");
      out.write("                                    <div class=\"product-img\">\n");
      out.write("                                        <img class=\"card-img\" src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-8 px-0\">\n");
      out.write("                                    <div class=\"card-body\">\n");
      out.write("                                        <h3 class=\"card-title mb-0 pb-0\">Nhật Quang LNN muốn đổi laptop cũ này lấy gì\n");
      out.write("                                            chưa\n");
      out.write("                                            biết</h3>\n");
      out.write("                                        <p class=\"card-text\">\n");
      out.write("                                            <small><i class=\"fas fa-clock icon-clock\"></i>12:AM 23/5/2001</small>\n");
      out.write("                                        </p>\n");
      out.write("                                        <div class=\"like-progress\">\n");
      out.write("                                            <div class=\"icon-heart\"><i class=\"fas fa-heart\"></i></div>\n");
      out.write("                                            <div class=\"progress w-75\" style=\"height: 5px\">\n");
      out.write("                                                <div class=\"progress-bar bg-danger\" style=\"width: 36%\"\n");
      out.write("                                                    role=\"progressbar\" style=\"width: 100%\" aria-valuenow=\"36\"\n");
      out.write("                                                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <p class=\"card-text\">\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-facebook\"></i>\n");
      out.write("                                                Phụ\n");
      out.write("                                                kiện điện tử</span>\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-linkedin\"></i>\n");
      out.write("                                                Đồ\n");
      out.write("                                                điện tử</span>\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-linkedin\"></i>\n");
      out.write("                                                Laptop</span>\n");
      out.write("                                        </p>\n");
      out.write("                                        <p class=\"card-text description\">Lorem ipsum dolor sit amet consectetur\n");
      out.write("                                            adipisicing\n");
      out.write("                                            elit. Vel\n");
      out.write("                                            obcaecati quidem quibusdam, quos magnam porro consequuntur quod nulla sequi\n");
      out.write("                                            voluptas ratione cumque quaerat magni iusto dolorum, voluptatibus quas\n");
      out.write("                                            tenetur\n");
      out.write("                                            nostrum.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- position abosolut, left: 0; bottom: 0 to align bottom this card \n");
      out.write("                                (the hieght of two left cards always equal to height of right card) -->\n");
      out.write("                        <div class=\"card no-gutters offer-box-products\" style=\"position: absolute; left: 0; bottom: 0;\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-4 px-0\">\n");
      out.write("                                    <div class=\"product-img\">\n");
      out.write("                                        <img class=\"card-img\" src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-8 px-0\">\n");
      out.write("                                    <div class=\"card-body\">\n");
      out.write("                                        <h3 class=\"card-title mb-0 pb-0\">Nhật Quang LNN muốn đổi laptop cũ này lấy gì\n");
      out.write("                                            chưa\n");
      out.write("                                            biết</h3>\n");
      out.write("                                        <p class=\"card-text\">\n");
      out.write("                                            <small><i class=\"fas fa-clock icon-clock\"></i>12:AM 23/5/2001</small>\n");
      out.write("                                        </p>\n");
      out.write("                                        <div class=\"like-progress\">\n");
      out.write("                                            <div class=\"icon-heart\"><i class=\"fas fa-heart\"></i></div>\n");
      out.write("                                            <div class=\"progress w-75\" style=\"height: 5px\">\n");
      out.write("                                                <div class=\"progress-bar bg-danger\" style=\"width: 36%\"\n");
      out.write("                                                    role=\"progressbar\" style=\"width: 100%\" aria-valuenow=\"36\"\n");
      out.write("                                                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <p class=\"card-text\">\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-facebook\"></i>\n");
      out.write("                                                Phụ\n");
      out.write("                                                kiện điện tử</span>\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-linkedin\"></i>\n");
      out.write("                                                Đồ\n");
      out.write("                                                điện tử</span>\n");
      out.write("                                            <span class=\"badge badge-pill badge-primary\"><i class=\"fab fa-linkedin\"></i>\n");
      out.write("                                                Laptop</span>\n");
      out.write("                                        </p>\n");
      out.write("                                        <p class=\"card-text description\">Lorem ipsum dolor sit amet consectetur\n");
      out.write("                                            adipisicing\n");
      out.write("                                            elit. Vel\n");
      out.write("                                            obcaecati quidem quibusdam, quos magnam porro consequuntur quod nulla sequi\n");
      out.write("                                            voluptas ratione cumque quaerat magni iusto dolorum, voluptatibus quas\n");
      out.write("                                            tenetur\n");
      out.write("                                            nostrum.</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- The right card -->\n");
      out.write("                <div class=\"col-md-4 the-right-card\">\n");
      out.write("                    <div class=\"card offer-box-products\">\n");
      out.write("                        <div class=\"product-img\"><img src=\"img-test-lastest-post/laptop.jpg\" alt=\"\"></div>\n");
      out.write("                        <div class=\"card-body pb-0 \">\n");
      out.write("                            <h2>Nhat Quang LNN</h2>\n");
      out.write("                            <h3 class=\"card-title mb-0 pb-0\">Muốn đổi chiếc laptop này lấy gì chưa biết!ss sss ss</h3>\n");
      out.write("                            <p class=\"card-text\">\n");
      out.write("                                <small><i class=\"fas fa-clock icon-clock\"></i>12:AM 23/5/2001</small>\n");
      out.write("                            </p>\n");
      out.write("                            <div class=\"like-progress\">\n");
      out.write("                                <div class=\"icon-heart\"><i class=\"fas fa-heart\"></i></div>\n");
      out.write("                                <div class=\"progress w-75\" style=\"height: 5px\">\n");
      out.write("                                    <div class=\"progress-bar bg-danger\" style=\"width: 36%\" role=\"progressbar\"\n");
      out.write("                                        style=\"width: 100%\" aria-valuenow=\"36\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <p class=\"description\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore, eos\n");
      out.write("                                atque omnis,\n");
      out.write("                                tenetur repellat soluta itaque provident perspiciatis nulla illum praesentium optio,\n");
      out.write("                                dolores reprehenderit aliquid! Ad excepturi quibusdam assumenda doloribus.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"footer\">\n");
      out.write("                            <div class=\"footer-to-align-center\">\n");
      out.write("                                <!-- chỉ nên lấy 3 cái, lấy 4 cái bể -->\n");
      out.write("                                <span class=\"badge badge-primary\"><i class=\"fab fa-facebook\"></i> Máy tính</span>\n");
      out.write("                                <span class=\"badge badge-primary\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                    tử</span>\n");
      out.write("                                <span class=\"badge badge-primary\"><i class=\"fab fa-linkedin\"></i> Thiết bị điện\n");
      out.write("                                    tử</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </dvi>\n");
      out.write("    </div>\n");
      out.write("    <!-- End the all post -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- The Exchanged Post -->\n");
      out.write("    <div class=\"theExchangedPost\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"postTitle\">\n");
      out.write("                    <h2>THE EXCHANGED POST</h2>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                        <img src=\"img-test-lastest-post/people1.jpg\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"username\">\n");
      out.write("                        <h3>Nhật Quang LNN</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- draw the line break -->\n");
      out.write("                    <div style=\"border-top: 1px solid #e3e9ef;\"></div>\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                        <img src=\"img-test-lastest-post/people-2.jpg\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"username\">\n");
      out.write("                        <h3>Mạnh Khôi NM</h3>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-8\">\n");
      out.write("                <div class=\"card left-card\">\n");
      out.write("                    <div class=\"card-title\">\n");
      out.write("                        <h3><span class=\"username\">Nhat Quang LNN</span> và <span class=\"username\">Nguyễn Mạnh Khôi</span></h3>\n");
      out.write("                        <div>đã đổi thành công Laptop cũ này lấy một\n");
      out.write("                            chiếc máy hút bụi đa năng </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"three-img\">\n");
      out.write("                        <img class=\"rounded-circle\" src=\"img-test-lastest-post/laptop.jpg\" alt=\"\">\n");
      out.write("                        <!-- change size to emphasis two product-img -->\n");
      out.write("                        <img style=\"width: 130px; height:130px; border: none\" src=\"img-test-lastest-post/handshake.jpg\"\n");
      out.write("                            alt=\"\">\n");
      out.write("                        <img class=\"rounded-circle\" src=\"img-test-lastest-post/clothes.jpg\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product-name-total\">\n");
      out.write("                        <span class=\"badge badge-success w-25 product-name\"> Máy tính</span>\n");
      out.write("                        <span class=\"badge badge-success w-25 product-name\"> Máy hút bụi</span>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Start copyright  -->\n");
      out.write("    <div class=\"footer-copyright\">\n");
      out.write("        <p class=\"footer-company\">All Rights Reserved. &copy; 2018 <a href=\"#\">ThewayShop</a> Design By :\n");
      out.write("            <a href=\"https://html.design/\">html design</a></p>\n");
      out.write("    </div>\n");
      out.write("    <!-- End copyright  -->\n");
      out.write("\n");
      out.write("    <a href=\"#\" id=\"back-to-top\" title=\"Back to top\" style=\"display: none;\">&uarr;</a>\n");
      out.write("\n");
      out.write("    <!-- ALL JS FILES -->\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- ALL PLUGINS -->\n");
      out.write("    <script src=\"js/jquery.superslides.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap-select.js\"></script>\n");
      out.write("    <script src=\"js/inewsticker.js\"></script>\n");
      out.write("    <script src=\"js/bootsnav.js.\"></script>\n");
      out.write("    <script src=\"js/images-loded.min.js\"></script>\n");
      out.write("    <script src=\"js/isotope.min.js\"></script>\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"js/baguetteBox.min.js\"></script>\n");
      out.write("    <script src=\"js/form-validator.min.js\"></script>\n");
      out.write("    <script src=\"js/contact-form-script.js\"></script>\n");
      out.write("    <script src=\"js/custom.js\"></script>\n");
      out.write("    <!-- Hữu Tình - 1208.03062021 - searchbar script -->\n");
      out.write("    <script src=\"js/searchbar.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
